/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagePageIdRouteImport } from './routes/page.$pageId'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiOverallReviewRouteImport } from './routes/api/overall-review'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageIdRoute = PagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverallReviewRoute = ApiOverallReviewRouteImport.update({
  id: '/api/overall-review',
  path: '/api/overall-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/page/$pageId': typeof PagePageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/page/$pageId': typeof PagePageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/page/$pageId': typeof PagePageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/api/overall-review'
    | '/api/review'
    | '/page/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/api/overall-review' | '/api/review' | '/page/$pageId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/api/overall-review'
    | '/api/review'
    | '/page/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ApiOverallReviewRoute: typeof ApiOverallReviewRoute
  ApiReviewRoute: typeof ApiReviewRoute
  PagePageIdRoute: typeof PagePageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageId': {
      id: '/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof PagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overall-review': {
      id: '/api/overall-review'
      path: '/api/overall-review'
      fullPath: '/api/overall-review'
      preLoaderRoute: typeof ApiOverallReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ApiOverallReviewRoute: ApiOverallReviewRoute,
  ApiReviewRoute: ApiReviewRoute,
  PagePageIdRoute: PagePageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
