/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestCollaborationRoomIdRouteImport } from './routes/test-collaboration.$roomId'
import { Route as PagePageIdRouteImport } from './routes/page.$pageId'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiOverallReviewRouteImport } from './routes/api/overall-review'
import { Route as ApiTestCollaborationRoomIdRouteImport } from './routes/api/test-collaboration/$roomId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCollaborationRoomIdRoute = TestCollaborationRoomIdRouteImport.update({
  id: '/test-collaboration/$roomId',
  path: '/test-collaboration/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageIdRoute = PagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverallReviewRoute = ApiOverallReviewRouteImport.update({
  id: '/api/overall-review',
  path: '/api/overall-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCollaborationRoomIdRoute =
  ApiTestCollaborationRoomIdRouteImport.update({
    id: '/api/test-collaboration/$roomId',
    path: '/api/test-collaboration/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/test-collaboration/$roomId': typeof TestCollaborationRoomIdRoute
  '/api/test-collaboration/$roomId': typeof ApiTestCollaborationRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/test-collaboration/$roomId': typeof TestCollaborationRoomIdRoute
  '/api/test-collaboration/$roomId': typeof ApiTestCollaborationRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/overall-review': typeof ApiOverallReviewRoute
  '/api/review': typeof ApiReviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/test-collaboration/$roomId': typeof TestCollaborationRoomIdRoute
  '/api/test-collaboration/$roomId': typeof ApiTestCollaborationRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/api/overall-review'
    | '/api/review'
    | '/api/transcribe'
    | '/page/$pageId'
    | '/test-collaboration/$roomId'
    | '/api/test-collaboration/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/api/overall-review'
    | '/api/review'
    | '/api/transcribe'
    | '/page/$pageId'
    | '/test-collaboration/$roomId'
    | '/api/test-collaboration/$roomId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/api/overall-review'
    | '/api/review'
    | '/api/transcribe'
    | '/page/$pageId'
    | '/test-collaboration/$roomId'
    | '/api/test-collaboration/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ApiOverallReviewRoute: typeof ApiOverallReviewRoute
  ApiReviewRoute: typeof ApiReviewRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  PagePageIdRoute: typeof PagePageIdRoute
  TestCollaborationRoomIdRoute: typeof TestCollaborationRoomIdRoute
  ApiTestCollaborationRoomIdRoute: typeof ApiTestCollaborationRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-collaboration/$roomId': {
      id: '/test-collaboration/$roomId'
      path: '/test-collaboration/$roomId'
      fullPath: '/test-collaboration/$roomId'
      preLoaderRoute: typeof TestCollaborationRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageId': {
      id: '/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof PagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overall-review': {
      id: '/api/overall-review'
      path: '/api/overall-review'
      fullPath: '/api/overall-review'
      preLoaderRoute: typeof ApiOverallReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-collaboration/$roomId': {
      id: '/api/test-collaboration/$roomId'
      path: '/api/test-collaboration/$roomId'
      fullPath: '/api/test-collaboration/$roomId'
      preLoaderRoute: typeof ApiTestCollaborationRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ApiOverallReviewRoute: ApiOverallReviewRoute,
  ApiReviewRoute: ApiReviewRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  PagePageIdRoute: PagePageIdRoute,
  TestCollaborationRoomIdRoute: TestCollaborationRoomIdRoute,
  ApiTestCollaborationRoomIdRoute: ApiTestCollaborationRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
